# RFID antenna specs
sensor_names:
  - 'rfid1'
  - 'rfid2'
rfid1:
  # sensor_name: 'rfid_antenna'
  sensor_direction: 0
  fov: 60
  range: 1
  shape: 'circular'
  reliability: 1
rfid2:
  # sensor_name: 'rfid_antenna'
  sensor_direction: -180
  fov: 60
  range: 1
  shape: 'circular'
  reliability: 1


min_distance: 0.2
navigation_pattern: 'wall_follow'
# navigation_pattern: 'boustrophedon'
